/**
 * @license
 *
 * Copyright IBM Corp. 2020, 2021
 *
 * This source code is licensed under the Apache-2.0 license found in the
 * LICENSE file in the root directory of this source tree.
 */

import { property, customElement } from 'lit-element';
import {
  formatVideoCaption,
  formatVideoDuration,
} from '@carbon/ibmdotcom-utilities/es/utilities/formatVideoCaption/formatVideoCaption.js';
import ddsSettings from '@carbon/ibmdotcom-utilities/es/utilities/settings/settings';
import DDSFeatureCardFooter from '../feature-card/feature-card-footer';
import CTAMixin from '../../component-mixins/cta/cta';
import { CTA_TYPE } from './defs';
import styles from './cta.scss';
import VideoCTAMixin from '../../component-mixins/cta/video';

const { stablePrefix: ddsPrefix } = ddsSettings;

/**
 * Feature CTA footer.
 *
 * @element dds-feature-cta-footer
 */
@customElement(`${ddsPrefix}-feature-cta-footer`)
class DDSFeatureCTAFooter extends VideoCTAMixin(CTAMixin(DDSFeatureCardFooter)) {
  /**
   * The CTA type.
   */
  @property({ reflect: true, attribute: 'cta-type' })
  ctaType = CTA_TYPE.REGULAR;

  /**
   * The formatter for the video caption, composed with the video name and the video duration.
   * Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatVideoCaption = formatVideoCaption;

  /**
   * The formatter for the video duration.
   * Should be changed upon the locale the UI is rendered with.
   */
  @property({ attribute: false })
  formatVideoDuration = formatVideoDuration;

  /**
   * The video duration.
   */
  @property({ type: Number, attribute: 'video-duration' })
  videoDuration?: number;

  /**
   * The video name.
   */
  @property({ attribute: 'video-name' })
  videoName?: string;

  /**
   * The video thumbnail URL.
   * Feature CTA does not support video thumbnail, and this property should never be set.
   */
  videoThumbnailUrl?: never;

  protected _getDefaultLabel() {
    switch (this.ctaType) {
      case 'download':
        return ' - This link downloads a file';
      case 'external':
        return ' - This link opens in a new tab';
      case 'video':
        return ' - This link plays a video';
      default:
        return '';
    }
  }

  updated() {
    if (!this._hasCopy) {
      this.shadowRoot?.querySelector(`a`)?.setAttribute('aria-label', this.altAriaLabel + this._getDefaultLabel());
    } else {
      this.shadowRoot?.querySelector(`a`)?.removeAttribute('aria-label');
    }
    if (this.ctaType === 'external') {
      this.shadowRoot?.querySelector(`a`)?.setAttribute('target', '_blank');
    } else {
      this.shadowRoot?.querySelector(`a`)?.removeAttribute('target');
    }
  }

  static styles = styles; // `styles` here is a `CSSResult` generated by custom WebPack loader
}

export default DDSFeatureCTAFooter;
